openapi: "3.0.3"
info:
  description: link-list-api
  title: LinkListApi
  version: ${project.version}
tags:
  - name: message
  - name: chat
  - name: authorization
  - name: user
paths:
  /api/v1/message:
    post:
      tags:
        - message
      operationId: addNewMessage
      description: Add new message to chat
      requestBody:
        description: AddMessageRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddMessageRequest"
        required: true
      responses:
        "201":
          description: MessageDto
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageDto"
    get:
      tags:
        - message
      operationId: getAllMessages
      description: Get all messages
      responses:
        "200":
          description: MessagesResponse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MessageDto"
  /api/v1/credentials-login:
    post:
      tags:
        - authorization
      operationId: loginWithCredentials
      description: Login with credentials
      requestBody:
        description: LoginRequest
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CredentialsLoginRequest"
        required: true
      responses:
        "200":
          description: TokenResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
  /api/v1/token-login:
    post:
      tags:
        - authorization
      operationId: loginWithRefreshToken
      description: Login with refresh-token
      requestBody:
        description: LoginRequest
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/RefreshTokenLoginRequest"
        required: true
      responses:
        "201":
          description: TokenResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
  /api/v1/user:
    get:
      tags:
        - user
      operationId: getCurrentUser
      description: Login with refresh-token
      responses:
        "200":
          description: UserResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
components:
  schemas:
    AddMessageRequest:
      type: object
      required:
        - content
        - receiverId
      properties:
        content:
          type: string
        receiverId:
          type: string
          format: uuid
    CredentialsLoginRequest:
      type: object
      required:
        - password
        - username
      properties:
        password:
          type: string
        username:
          type: string
    RefreshTokenLoginRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
    TokenResponse:
      type: object
      required:
        - token
      properties:
        access_token:
          type: string
        expires_in:
          type: string
        refresh_expires_in:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        id_token:
          type: string
    UserResponse:
      type: object
      required:
        - token
      properties:
        username:
          type: string
        email:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        userId:
          type: string
    MessageDto:
      type: object
      required:
        - content
        - senderId
        - receiverId
        - timestamp
      properties:
        content:
          type: string
        senderId:
          type: string
          format: uuid
        receiverId:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time