openapi: "3.0.3"
info:
  description: link-list-api
  title: LinkListApi
  version: ${project.version}
tags:
  - name: message
  - name: chat
paths:
  /api/v1/message:
    post:
      tags:
        - message
      operationId: addNewMessage
      description: Add new message to chat
      requestBody:
        description: AddMessageRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddMessageRequest"
        required: true
      responses:
        "201":
          description: MessageDto
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageDto"
    get:
      tags:
        - message
      operationId: getAllMessages
      description: Get all messages
      responses:
        "200":
          description: MessagesResponse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MessageDto"
components:
  schemas:
    AddMessageRequest:
      type: object
      required:
        - content
        - receiverId
      properties:
        content:
          type: string
        receiverId:
          type: string
          format: uuid
    MessageDto:
      type: object
      required:
        - content
        - senderId
        - receiverId
        - timestamp
      properties:
        content:
          type: string
        senderId:
          type: string
          format: uuid
        receiverId:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time